### ISSUE TITLE
TaiCoL 海報文案 - 「臺灣物種有多少？」

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/intl-day-biodiversity#5]

**Comment by lyh-yihsuan** [comment]
臺灣物種名錄 (Catalogue of Life in Taiwan, TaiCoL) 是為了使臺灣有一最新、最正確的物種學名資料庫，以推動生物多樣性資訊整合而成立。2002 年，臺灣物種名錄資料庫建立，並於2003 年正式對外公開網站(http://taibnet.sinica.edu.tw)。

現網站以物種名錄為主，亦有專家名錄及物種保育入侵資訊。網站除提供學名及中文俗名查詢服務之外，亦提供學名核對、名錄下載，並支援合作網站之學名連結，以相互擷取物種相關資料。

![image](https://user-images.githubusercontent.com/32127001/40286929-b6c13700-5cdc-11e8-84b7-855895831c34.png)

臺灣的生物多樣性程度非常高，經 870 位以上專家通力合作，目前 TaiCoL 已收錄逾 59,000 種有效物種。本計畫將持續修訂與即時更新資料庫，並於網站呈現最新資訊。

![image](https://user-images.githubusercontent.com/32127001/40286944-cdca227c-5cdc-11e8-80df-0c9ebd487c51.png)

**Comment by lyh-yihsuan** [comment]
![image](https://user-images.githubusercontent.com/32127001/40287195-4e24c02a-5cde-11e8-8a33-1dd917b5ef89.png)

**Comment by cjk-halodule** [comment]
謝謝！很美。
