### ISSUE TITLE
TaiBIF 海報文案 - 「臺灣物種在哪裡？」

### ISSUE THREAD

**Issue by cjk-halodule** [TaiBIF/intl-day-biodiversity#6]
請以目前海報文案修改。

**Comment by lyh-yihsuan** [comment]
臺灣生物多樣性資訊機構 (Taiwan Biodiversity Information Facility, TaiBIF) 是全球生物多樣性資訊機構 (GBIF) 在臺灣的國家節點，主要任務為推動、建置臺灣生物多樣性資訊相關基礎建設，以及推動標準化資料之公開授權，供任何使用者合理使用。目前 TaiBIF 所流通的資料是採創用 CC 授權條款 (Creative Commons license)。

![image](https://user-images.githubusercontent.com/32127001/40287052-71ab172a-5cdd-11e8-9835-166e0102fdf9.png)

2018 年 5 月，臺灣已有 43 份資料集、2,011,682 筆物種出現紀錄，與 96,950 筆名錄資料，透過 TaiBIF 發布至 GBIF。使用 GBIF 資料的科學研究發表中，44 篇有臺灣學者的參與，15 篇談及臺灣的生物多樣性。

![image](https://user-images.githubusercontent.com/32127001/40287070-81f7eb76-5cdd-11e8-8655-7cf4dc0e52d3.png)

物種出現紀錄資料覆蓋密度雖具參考價值，卻也可能與真實生物多樣性現況不盡相符。如目前TaiBIF網站呈現之臺灣藍鵲分布圖中，無臺灣藍鵲出現紀錄之處，並非表示臺灣藍鵲一定未分布於該處，有可能是因該區未曾進行過調查，或調查時剛好未發現臺灣藍鵲之故。若您有任何可填補資料缺口的資料來源，歡迎與 TaiBIF 連繫，提高更多資料的能見度。

![image](https://user-images.githubusercontent.com/32127001/40287083-948d5f1e-5cdd-11e8-9384-9eec90dc5140.png)

**Comment by lyh-yihsuan** [comment]
![image](https://user-images.githubusercontent.com/32127001/40287170-18da9ffc-5cde-11e8-90e2-1a34b9d1fa52.png)
